[tool.uv.workspace]
members = [
    "common",
    "transcript",
    "summarize",
    "scrape"
]

[tool.uv.sources]
common = { workspace = true }
transcript = { workspace = true }
summarize = { workspace = true }
scrape = { workspace = true }
